version: '3'
networks:
 udrepository:

services:
  ud-repository-api:
     image: damillano93/ud-repository-api
     container_name: ud-repository-api
     restart: on-failure
     env_file:
        - .env
     networks:
        - udrepository
     labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ud-repository-api.rule=Host(`apirepository.damillano.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.ud-repository-api.middlewares=ud-repository-api-stripprefix"
      - "traefik.http.middlewares.ud-repository-api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.ud-repository-api.tls=true"
      - "traefik.http.routers.ud-repository-api.tls.certresolver=le"
      - "traefik.http.services.ud-repository-api.loadbalancer.server.port=80"           
networks:
  udrepository:
    external: true
